nissan9/os_left/os_driver:
 ros__parameters:
    sensor_hostname: 'os1-991943001101.local'
    udp_dest: '192.168.2.100'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x20'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'LEGACY'
    metadata: ''
    sensor_frame: 'nissan9/os_left'
    lidar_frame: 'nissan9/os_left_data_frame'
    imu_frame: 'nissan9/os_left_imu_data_frame'
    lidar_port: 7503
    imu_port: 7502
    use_system_default_qos: true
nissan9/os_right/os_driver:
 ros__parameters:
    sensor_hostname: 'os-122226002956.local'
    udp_dest: '192.168.2.100'
    mtp_dest: ''
    mtp_main: false
    lidar_mode: '1024x20'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: 'RNG19_RFL8_SIG16_NIR16'
    metadata: ''
    sensor_frame: 'nissan9/os_right'
    lidar_frame: 'nissan9/os_right_data_frame'
    imu_frame: 'nissan9/os_right_imu_data_frame'
    lidar_port: 7505
    imu_port: 7504
    use_system_default_qos: true
